/* TEAMS TABLE */
CREATE table teams (
    teamid int PRIMARY KEY,
    country TEXT,
    name TEXT
);

/* EACH ROW IS A TEAM/NATIONAL TEAM FROM OUR SCRIPT */
insert or ignore into teams values ("359", "eng", "arsenal");
insert or ignore into teams values ("362", "eng", "aston villa");
insert or ignore into teams values ("363", "eng", "chelsea");
insert or ignore into teams values ("368", "eng", "everton");
insert or ignore into teams values ("370", "eng", "fulham");
insert or ignore into teams values ("364", "eng", "liverpool");
insert or ignore into teams values ("382", "eng", "manchester city");
insert or ignore into teams values ("360", "eng", "manchester united");
insert or ignore into teams values ("361", "eng", "newcastle united");
insert or ignore into teams values ("381", "eng", "norwich city");
insert or ignore into teams values ("334", "eng", "queens park rangers");
insert or ignore into teams values ("338", "eng", "reading");
insert or ignore into teams values ("376", "eng", "southampton");
insert or ignore into teams values ("336", "eng", "stoke city");
insert or ignore into teams values ("366", "eng", "sunderland");
insert or ignore into teams values ("318", "eng", "swansea city");
insert or ignore into teams values ("367", "eng", "tottenham hotspur");
insert or ignore into teams values ("383", "eng", "west bromwich albion");
insert or ignore into teams values ("371", "eng", "west ham united");
insert or ignore into teams values ("350", "eng", "wigan athletic");
insert or ignore into teams values ("93", "esp", "athletic bilbao");
insert or ignore into teams values ("1068", "esp", "atletico madrid");
insert or ignore into teams values ("83", "esp", "barcelona");
insert or ignore into teams values ("85", "esp", "celta vigo");
insert or ignore into teams values ("90", "esp", "deportivo la coruña");
insert or ignore into teams values ("88", "esp", "espanyol");
insert or ignore into teams values ("2922", "esp", "getafe");
insert or ignore into teams values ("3747", "esp", "granada");
insert or ignore into teams values ("1538", "esp", "levante");
insert or ignore into teams values ("99", "esp", "malaga");
insert or ignore into teams values ("84", "esp", "mallorca");
insert or ignore into teams values ("97", "esp", "osasuna");
insert or ignore into teams values ("101", "esp", "rayo vallecano");
insert or ignore into teams values ("244", "esp", "real betis");
insert or ignore into teams values ("86", "esp", "real madrid");
insert or ignore into teams values ("89", "esp", "real sociedad");
insert or ignore into teams values ("91", "esp", "real zaragoza");
insert or ignore into teams values ("243", "esp", "sevilla fc");
insert or ignore into teams values ("94", "esp", "valencia");
insert or ignore into teams values ("95", "esp", "real valladolid");
insert or ignore into teams values ("11121", "esp", "ad alcorcon");
insert or ignore into teams values ("6832", "esp", "almeria");
insert or ignore into teams values ("5462", "esp", "barcelona b");
insert or ignore into teams values ("11487", "esp", "cd sabadell");
insert or ignore into teams values ("8447", "esp", "cordoba");
insert or ignore into teams values ("3751", "esp", "elche");
insert or ignore into teams values ("9812", "esp", "girona");
insert or ignore into teams values ("11484", "esp", "guadalajara");
insert or ignore into teams values ("6833", "esp", "hercules");
insert or ignore into teams values ("5413", "esp", "huesca");
insert or ignore into teams values ("98", "esp", "las palmas");
insert or ignore into teams values ("7266", "esp", "lugo");
insert or ignore into teams values ("4515", "esp", "mirandes");
insert or ignore into teams values ("2738", "esp", "murcia");
insert or ignore into teams values ("100", "esp", "numancia");
insert or ignore into teams values ("5463", "esp", "ponferradina");
insert or ignore into teams values ("87", "esp", "racing santander");
insert or ignore into teams values ("7000", "esp", "real madrid castilla");
insert or ignore into teams values ("2571", "esp", "recreativo huelva");
insert or ignore into teams values ("3788", "esp", "sporting gijon");
insert or ignore into teams values ("102", "esp", "villarreal");
insert or ignore into teams values ("3835", "esp", "xerez");
insert or ignore into teams values ("103", "ita", "ac milan");
insert or ignore into teams values ("104", "ita", "as roma");
insert or ignore into teams values ("105", "ita", "atalanta");
insert or ignore into teams values ("107", "ita", "bologna");
insert or ignore into teams values ("2925", "ita", "cagliari");
insert or ignore into teams values ("3258", "ita", "catania");
insert or ignore into teams values ("238", "ita", "chievo verona");
insert or ignore into teams values ("109", "ita", "fiorentina");
insert or ignore into teams values ("3263", "ita", "genoa");
insert or ignore into teams values ("110", "ita", "internazionale");
insert or ignore into teams values ("111", "ita", "juventus");
insert or ignore into teams values ("112", "ita", "lazio");
insert or ignore into teams values ("114", "ita", "napoli");
insert or ignore into teams values ("2923", "ita", "palermo");
insert or ignore into teams values ("115", "ita", "parma");
insert or ignore into teams values ("2734", "ita", "sampdoria");
insert or ignore into teams values ("2735", "ita", "siena");
insert or ignore into teams values ("239", "ita", "torino");
insert or ignore into teams values ("118", "ita", "udinese");
insert or ignore into teams values ("3290", "ita", "us pescara");
insert or ignore into teams values ("3346", "ita", "ascoli");
insert or ignore into teams values ("106", "ita", "bari");
insert or ignore into teams values ("108", "ita", "brescia");
insert or ignore into teams values ("3337", "ita", "cesena");
insert or ignore into teams values ("3943", "ita", "cittadella");
insert or ignore into teams values ("3173", "ita", "crotone");
insert or ignore into teams values ("2574", "ita", "empoli");
insert or ignore into teams values ("3955", "ita", "grosseto");
insert or ignore into teams values ("119", "ita", "hellas verona");
insert or ignore into teams values ("3975", "ita", "juve stabia");
insert or ignore into teams values ("3969", "ita", "lanciano");
insert or ignore into teams values ("2926", "ita", "livorno");
insert or ignore into teams values ("2573", "ita", "modena");
insert or ignore into teams values ("3954", "ita", "novara");
insert or ignore into teams values ("3952", "ita", "padova");
insert or ignore into teams values ("3995", "ita", "pro vercelli");
insert or ignore into teams values ("117", "ita", "reggina");
insert or ignore into teams values ("3997", "ita", "sassuolo");
insert or ignore into teams values ("4056", "ita", "spezia");
insert or ignore into teams values ("3175", "ita", "ternana");
insert or ignore into teams values ("9346", "ita", "varese");
insert or ignore into teams values ("120", "ita", "vicenza");
insert or ignore into teams values ("131", "ger", "bayer leverkusen");
insert or ignore into teams values ("132", "ger", "bayern munich");
insert or ignore into teams values ("124", "ger", "borussia dortmund");
insert or ignore into teams values ("268", "ger", "borussia monchengladbach");
insert or ignore into teams values ("125", "ger", "eintracht frankfurt");
insert or ignore into teams values ("3841", "ger", "fc augsburg");
insert or ignore into teams values ("9707", "ger", "fortuna düsseldorf");
insert or ignore into teams values ("127", "ger", "hamburg sv");
insert or ignore into teams values ("2428", "ger", "hannover 96");
insert or ignore into teams values ("2950", "ger", "mainz");
insert or ignore into teams values ("269", "ger", "nurnberg");
insert or ignore into teams values ("126", "ger", "sc freiburg");
insert or ignore into teams values ("133", "ger", "schalke 04");
insert or ignore into teams values ("3070", "ger", "spvgg greuther furth");
insert or ignore into teams values ("7911", "ger", "tsg hoffenheim");
insert or ignore into teams values ("134", "ger", "vfb stuttgart");
insert or ignore into teams values ("138", "ger", "vfl wolfsburg");
insert or ignore into teams values ("137", "ger", "werder bremen");
insert or ignore into teams values ("7017", "ger", "dynamo dresden");
insert or ignore into teams values ("123", "ger", "energie cottbus");
insert or ignore into teams values ("122", "ger", "fc cologne");
insert or ignore into teams values ("3849", "ger", "fc erzgebirge aue");
insert or ignore into teams values ("6367", "ger", "fc ingolstadt 04");
insert or ignore into teams values ("598", "ger", "fc union berlin");
insert or ignore into teams values ("6608", "ger", "fsv frankfurt");
insert or ignore into teams values ("129", "ger", "hertha berlin");
insert or ignore into teams values ("130", "ger", "kaiserslautern");
insert or ignore into teams values ("3308", "ger", "msv duisburg");
insert or ignore into teams values ("3307", "ger", "sc paderborn 07");
insert or ignore into teams values ("11017", "ger", "ssv jahn regensburg");
insert or ignore into teams values ("270", "ger", "st pauli");
insert or ignore into teams values ("6392", "ger", "sv sandhausen");
insert or ignore into teams values ("135", "ger", "tsv 1860 munich");
insert or ignore into teams values ("3067", "ger", "tsv eintracht braunschweig");
insert or ignore into teams values ("121", "ger", "vfl bochum");
insert or ignore into teams values ("3770", "ger", "vfr aalen");
insert or ignore into teams values ("2503", "fra", "ac ajaccio");
insert or ignore into teams values ("3267", "fra", "as nancy lorraine");
insert or ignore into teams values ("173", "fra", "bastia");
insert or ignore into teams values ("159", "fra", "bordeaux");
insert or ignore into teams values ("6997", "fra", "brest");
insert or ignore into teams values ("11058", "fra", "evian thonon gaillard");
insert or ignore into teams values ("166", "fra", "lille");
insert or ignore into teams values ("273", "fra", "lorient");
insert or ignore into teams values ("167", "fra", "lyon");
insert or ignore into teams values ("176", "fra", "marseille");
insert or ignore into teams values ("274", "fra", "montpellier");
insert or ignore into teams values ("2502", "fra", "nice");
insert or ignore into teams values ("160", "fra", "paris saint-germain");
insert or ignore into teams values ("272", "fra", "sochaux");
insert or ignore into teams values ("178", "fra", "st etienne");
insert or ignore into teams values ("3243", "fra", "stade de reims");
insert or ignore into teams values ("169", "fra", "stade rennes");
insert or ignore into teams values ("179", "fra", "toulouse");
insert or ignore into teams values ("170", "fra", "troyes");
insert or ignore into teams values ("6732", "fra", "valenciennes");
insert or ignore into teams values ("172", "fra", "aj auxerre");
insert or ignore into teams values ("7707", "fra", "ajaccio gfco");
insert or ignore into teams values ("7868", "fra", "angers");
insert or ignore into teams values ("10373", "fra", "arles");
insert or ignore into teams values ("174", "fra", "as monaco");
insert or ignore into teams values ("2927", "fra", "caen");
insert or ignore into teams values ("2995", "fra", "chateauroux");
insert or ignore into teams values ("3171", "fra", "clermont foot");
insert or ignore into teams values ("3170", "fra", "dijon fco");
insert or ignore into teams values ("3207", "fra", "fc istres");
insert or ignore into teams values ("171", "fra", "guingamp");
insert or ignore into teams values ("3236", "fra", "le havre ac");
insert or ignore into teams values ("2697", "fra", "le mans");
insert or ignore into teams values ("175", "fra", "lens");
insert or ignore into teams values ("165", "fra", "nantes");
insert or ignore into teams values ("7730", "fra", "nimes");
insert or ignore into teams values ("6990", "fra", "niort");
insert or ignore into teams values ("168", "fra", "sedan");
insert or ignore into teams values ("3266", "fra", "stade laval");
insert or ignore into teams values ("6992", "fra", "tours");
insert or ignore into teams values ("263", "sco", "aberdeen");
insert or ignore into teams values ("256", "sco", "celtic");
insert or ignore into teams values ("261", "sco", "dundee");
insert or ignore into teams values ("264", "sco", "dundee united");
insert or ignore into teams values ("262", "sco", "heart of midlothian");
insert or ignore into teams values ("258", "sco", "hibernian");
insert or ignore into teams values ("253", "sco", "inverness caledonian thistle");
insert or ignore into teams values ("260", "sco", "kilmarnock");
insert or ignore into teams values ("266", "sco", "motherwell");
insert or ignore into teams values ("251", "sco", "ross county");
insert or ignore into teams values ("267", "sco", "st johnstone");
insert or ignore into teams values ("250", "sco", "st mirren");
insert or ignore into teams values ("2500", "sco", "airdrie united");
insert or ignore into teams values ("410", "sco", "cowdenbeath");
insert or ignore into teams values ("415", "sco", "dumbarton");
insert or ignore into teams values ("261", "sco", "dundee");
insert or ignore into teams values ("265", "sco", "dunfermline athletic");
insert or ignore into teams values ("254", "sco", "falkirk");
insert or ignore into teams values ("411", "sco", "greenock morton");
insert or ignore into teams values ("409", "sco", "hamilton academical");
insert or ignore into teams values ("259", "sco", "livingston");
insert or ignore into teams values ("247", "sco", "partick thistle");
insert or ignore into teams values ("249", "sco", "raith rovers");
insert or ignore into teams values ("420", "sco", "albion rovers");
insert or ignore into teams values ("403", "sco", "alloa athletic");
insert or ignore into teams values ("252", "sco", "arbroath");
insert or ignore into teams values ("248", "sco", "ayr united");
insert or ignore into teams values ("413", "sco", "brechin city");
insert or ignore into teams values ("421", "sco", "east fife");
insert or ignore into teams values ("408", "sco", "forfar athletic");
insert or ignore into teams values ("406", "sco", "queen of the south");
insert or ignore into teams values ("405", "sco", "stenhousemuir");
insert or ignore into teams values ("407", "sco", "stranraer");
insert or ignore into teams values ("7166", "sco", "annan athletic");
insert or ignore into teams values ("412", "sco", "berwick rangers");
insert or ignore into teams values ("255", "sco", "clyde");
insert or ignore into teams values ("418", "sco", "east stirlingshire");
insert or ignore into teams values ("419", "sco", "elgin city");
insert or ignore into teams values ("414", "sco", "montrose");
insert or ignore into teams values ("416", "sco", "peterhead");
insert or ignore into teams values ("422", "sco", "queen's park");
insert or ignore into teams values ("257", "sco", "rangers");
insert or ignore into teams values ("417", "sco", "stirling albion");
insert or ignore into teams values ("2726", "ned", "ado den haag");
insert or ignore into teams values ("139", "ned", "ajax amsterdam");
insert or ignore into teams values ("140", "ned", "az alkmaar");
insert or ignore into teams values ("145", "ned", "fc groningen");
insert or ignore into teams values ("153", "ned", "fc utrecht");
insert or ignore into teams values ("2565", "ned", "pec zwolle");
insert or ignore into teams values ("142", "ned", "feyenoord rotterdam");
insert or ignore into teams values ("146", "ned", "heerenveen");
insert or ignore into teams values ("141", "ned", "nac breda");
insert or ignore into teams values ("147", "ned", "nec nijmegen");
insert or ignore into teams values ("148", "ned", "psv eindhoven");
insert or ignore into teams values ("155", "ned", "rkc waalwijk");
insert or ignore into teams values ("149", "ned", "roda jc kerkrade");
insert or ignore into teams values ("3708", "ned", "sc heracles almelo");
insert or ignore into teams values ("152", "ned", "twente enschede");
insert or ignore into teams values ("154", "ned", "vitesse arnhem");
insert or ignore into teams values ("3731", "ned", "vvv venlo");
insert or ignore into teams values ("156", "ned", "willem ii tilburg");
insert or ignore into teams values ("3727", "ned", "agovv apeldoorn");
insert or ignore into teams values ("5291", "ned", "almere city");
insert or ignore into teams values ("3729", "ned", "bv veendam");
insert or ignore into teams values ("3736", "ned", "cambuur leeuwarden");
insert or ignore into teams values ("144", "ned", "de graafschap");
insert or ignore into teams values ("4426", "ned", "dordrecht '90");
insert or ignore into teams values ("2566", "ned", "excelsior");
insert or ignore into teams values ("271", "ned", "fc den bosch");
insert or ignore into teams values ("3732", "ned", "fc eindhoven");
insert or ignore into teams values ("3707", "ned", "fc emmen vv");
insert or ignore into teams values ("3728", "ned", "fc oss");
insert or ignore into teams values ("2727", "ned", "fc volendam");
insert or ignore into teams values ("143", "ned", "fortuna sittard");
insert or ignore into teams values ("3706", "ned", "go ahead eagles");
insert or ignore into teams values ("3775", "ned", "helmond sport");
insert or ignore into teams values ("3730", "ned", "mvv maastricht");
insert or ignore into teams values ("3735", "ned", "sc stormvogels telstar");
insert or ignore into teams values ("151", "ned", "sparta rotterdam");
insert or ignore into teams values ("3698", "por", "academica de coimbra");
insert or ignore into teams values ("1423", "por", "beira mar");
insert or ignore into teams values ("1929", "por", "benfica");
insert or ignore into teams values ("2994", "por", "braga");
insert or ignore into teams values ("3472", "por", "cd nacional de madeira");
insert or ignore into teams values ("12216", "por", "estoril");
insert or ignore into teams values ("437", "por", "fc porto");
insert or ignore into teams values ("3699", "por", "gil vicente");
insert or ignore into teams values ("5309", "por", "guimaraes");
insert or ignore into teams values ("552", "por", "maritimo");
insert or ignore into teams values ("3696", "por", "moreirense");
insert or ignore into teams values ("3712", "por", "olhanense");
insert or ignore into teams values ("3713", "por", "paços de ferreira");
insert or ignore into teams values ("3822", "por", "rio ave");
insert or ignore into teams values ("2250", "por", "sporting lisbon");
insert or ignore into teams values ("5308", "por", "vitoria setubal");
insert or ignore into teams values ("172", "fra", "aj auxerre");
insert or ignore into teams values ("7707", "fra", "ajaccio gfco");
insert or ignore into teams values ("7868", "fra", "angers");
insert or ignore into teams values ("10373", "fra", "arles");
insert or ignore into teams values ("174", "fra", "as monaco");
insert or ignore into teams values ("2927", "fra", "caen");
insert or ignore into teams values ("2995", "fra", "chateauroux");
insert or ignore into teams values ("3171", "fra", "clermont foot");
insert or ignore into teams values ("3170", "fra", "dijon fco");
insert or ignore into teams values ("3207", "fra", "fc istres");
insert or ignore into teams values ("171", "fra", "guingamp");
insert or ignore into teams values ("3236", "fra", "le havre ac");
insert or ignore into teams values ("2697", "fra", "le mans");
insert or ignore into teams values ("175", "fra", "lens");
insert or ignore into teams values ("165", "fra", "nantes");
insert or ignore into teams values ("7730", "fra", "nimes");
insert or ignore into teams values ("6990", "fra", "niort");
insert or ignore into teams values ("168", "fra", "sedan");
insert or ignore into teams values ("3266", "fra", "stade laval");
insert or ignore into teams values ("6992", "fra", "tours");
insert or ignore into teams values ("1960", "rus", "alania vladikavkaz");
insert or ignore into teams values ("593", "rus", "anzhi makhachkala");
insert or ignore into teams values ("1963", "rus", "cska moscow");
insert or ignore into teams values ("596", "rus", "dinamo moscow");
insert or ignore into teams values ("3791", "rus", "fk amkar perm'");
insert or ignore into teams values ("3852", "rus", "fk rostov-na-donu");
insert or ignore into teams values ("3851", "rus", "fk rubin kazan");
insert or ignore into teams values ("11336", "rus", "krasnodar");
insert or ignore into teams values ("7425", "rus", "kuban krasnodar");
insert or ignore into teams values ("442", "rus", "lokomotiv moscow");
insert or ignore into teams values ("12534", "rus", "mordovia saransk");
insert or ignore into teams values ("3850", "rus", "pfk samara kryliya sovetov");
insert or ignore into teams values ("1941", "rus", "spartak moscow");
insert or ignore into teams values ("2991", "rus", "terek grozny");
insert or ignore into teams values ("11288", "rus", "volga nizhny novgorod");
insert or ignore into teams values ("2533", "rus", "zenit st petersburg");
insert or ignore into teams values ("227", "mex", "américa");
insert or ignore into teams values ("226", "mex", "atlante");
insert or ignore into teams values ("216", "mex", "atlas");
insert or ignore into teams values ("224", "mex", "chiapas");
insert or ignore into teams values ("218", "mex", "cruz azul");
insert or ignore into teams values ("219", "mex", "guadalajara");
insert or ignore into teams values ("228", "mex", "león");
insert or ignore into teams values ("220", "mex", "monterrey");
insert or ignore into teams values ("221", "mex", "morelia");
insert or ignore into teams values ("234", "mex", "pachuca");
insert or ignore into teams values ("231", "mex", "puebla");
insert or ignore into teams values ("222", "mex", "querétaro");
insert or ignore into teams values ("2490", "mex", "san luis");
insert or ignore into teams values ("225", "mex", "santos");
insert or ignore into teams values ("10125", "mex", "tijuana");
insert or ignore into teams values ("223", "mex", "toluca");
insert or ignore into teams values ("232", "mex", "u.a.n.l");
insert or ignore into teams values ("233", "mex", "unam");
insert or ignore into teams values ("585", "national", "albania");
insert or ignore into teams values ("624", "national", "algeria");
insert or ignore into teams values ("587", "national", "andorra");
insert or ignore into teams values ("653", "national", "angola");
insert or ignore into teams values ("202", "national", "argentina");
insert or ignore into teams values ("579", "national", "armenia");
insert or ignore into teams values ("628", "national", "australia");
insert or ignore into teams values ("474", "national", "austria");
insert or ignore into teams values ("581", "national", "azerbaijan");
insert or ignore into teams values ("4381", "national", "bahrain");
insert or ignore into teams values ("583", "national", "belarus");
insert or ignore into teams values ("2844", "national", "benin");
insert or ignore into teams values ("204", "national", "bolivia");
insert or ignore into teams values ("452", "national", "bosnia-herzegovina");
insert or ignore into teams values ("4245", "national", "botswana");
insert or ignore into teams values ("462", "national", "bulgaria");
insert or ignore into teams values ("2845", "national", "burkina faso");
insert or ignore into teams values ("656", "national", "cameroon");
insert or ignore into teams values ("2597", "national", "cape verde islands");
insert or ignore into teams values ("10528", "national", "central african republic");
insert or ignore into teams values ("207", "national", "chile");
insert or ignore into teams values ("658", "national", "china");
insert or ignore into teams values ("208", "national", "colombia");
insert or ignore into teams values ("4276", "national", "congo");
insert or ignore into teams values ("2850", "national", "congo dr");
insert or ignore into teams values ("214", "national", "costa rica");
insert or ignore into teams values ("445", "national", "cyprus");
insert or ignore into teams values ("450", "national", "czech republic");
insert or ignore into teams values ("479", "national", "denmark");
insert or ignore into teams values ("209", "national", "ecuador");
insert or ignore into teams values ("2620", "national", "egypt");
insert or ignore into teams values ("448", "national", "england");
insert or ignore into teams values ("8938", "national", "equatorial guinea");
insert or ignore into teams values ("444", "national", "estonia");
insert or ignore into teams values ("5777", "national", "ethiopia");
insert or ignore into teams values ("447", "national", "faroe islands");
insert or ignore into teams values ("458", "national", "finland");
insert or ignore into teams values ("478", "national", "france");
insert or ignore into teams values ("4231", "national", "gabon");
insert or ignore into teams values ("7368", "national", "gambia");
insert or ignore into teams values ("584", "national", "georgia");
insert or ignore into teams values ("481", "national", "germany");
insert or ignore into teams values ("4469", "national", "ghana");
insert or ignore into teams values ("455", "national", "greece");
insert or ignore into teams values ("2847", "national", "guinea");
insert or ignore into teams values ("215", "national", "honduras");
insert or ignore into teams values ("480", "national", "hungary");
insert or ignore into teams values ("470", "national", "iceland");
insert or ignore into teams values ("4895", "national", "indonesia");
insert or ignore into teams values ("469", "national", "iran");
insert or ignore into teams values ("4375", "national", "iraq");
insert or ignore into teams values ("476", "national", "ireland");
insert or ignore into teams values ("461", "national", "israel");
insert or ignore into teams values ("162", "national", "italy");
insert or ignore into teams values ("4789", "national", "ivory coast");
insert or ignore into teams values ("1038", "national", "jamaica");
insert or ignore into teams values ("627", "national", "japan");
insert or ignore into teams values ("2917", "national", "jordan");
insert or ignore into teams values ("2619", "national", "kazakhstan");
insert or ignore into teams values ("2848", "national", "kenya");
insert or ignore into teams values ("841", "national", "kuwait");
insert or ignore into teams values ("456", "national", "latvia");
insert or ignore into teams values ("4388", "national", "lebanon");
insert or ignore into teams values ("6640", "national", "lesotho");
insert or ignore into teams values ("4205", "national", "liberia");
insert or ignore into teams values ("2621", "national", "libya");
insert or ignore into teams values ("589", "national", "liechtenstein");
insert or ignore into teams values ("460", "national", "lithuania");
insert or ignore into teams values ("582", "national", "luxembourg");
insert or ignore into teams values ("4325", "national", "malawi");
insert or ignore into teams values ("2849", "national", "mali");
insert or ignore into teams values ("453", "national", "malta");
insert or ignore into teams values ("203", "national", "mexico");
insert or ignore into teams values ("483", "national", "moldova");
insert or ignore into teams values ("6775", "national", "montenegro");
insert or ignore into teams values ("2869", "national", "morocco");
insert or ignore into teams values ("8939", "national", "mozambique");
insert or ignore into teams values ("6725", "national", "namibia");
insert or ignore into teams values ("449", "national", "netherlands");
insert or ignore into teams values ("8937", "national", "niger");
insert or ignore into teams values ("657", "national", "nigeria");
insert or ignore into teams values ("4860", "national", "north korea");
insert or ignore into teams values ("586", "national", "northern ireland");
insert or ignore into teams values ("464", "national", "norway");
insert or ignore into teams values ("2841", "national", "oman");
insert or ignore into teams values ("2659", "national", "panama");
insert or ignore into teams values ("210", "national", "paraguay");
insert or ignore into teams values ("211", "national", "peru");
insert or ignore into teams values ("471", "national", "poland");
insert or ignore into teams values ("482", "national", "portugal");
insert or ignore into teams values ("4398", "national", "qatar");
insert or ignore into teams values ("473", "national", "romania");
insert or ignore into teams values ("454", "national", "russia");
insert or ignore into teams values ("2851", "national", "rwanda");
insert or ignore into teams values ("588", "national", "san marino");
insert or ignore into teams values ("655", "national", "saudi arabia");
insert or ignore into teams values ("654", "national", "senegal");
insert or ignore into teams values ("8600", "national", "sierra leone");
insert or ignore into teams values ("4384", "national", "singapore");
insert or ignore into teams values ("468", "national", "slovakia");
insert or ignore into teams values ("472", "national", "slovenia");
insert or ignore into teams values ("467", "national", "south africa");
insert or ignore into teams values ("451", "national", "south korea");
insert or ignore into teams values ("164", "national", "spain");
insert or ignore into teams values ("4319", "national", "sudan");
insert or ignore into teams values ("466", "national", "sweden");
insert or ignore into teams values ("475", "national", "switzerland");
insert or ignore into teams values ("4380", "national", "syria");
insert or ignore into teams values ("5778", "national", "tanzania");
insert or ignore into teams values ("4396", "national", "thailand");
insert or ignore into teams values ("4356", "national", "togo");
insert or ignore into teams values ("659", "national", "tunisia");
insert or ignore into teams values ("465", "national", "turkey");
insert or ignore into teams values ("4211", "national", "uganda");
insert or ignore into teams values ("457", "national", "ukraine");
insert or ignore into teams values ("4397", "national", "united arab emirates");
insert or ignore into teams values ("660", "national", "united states");
insert or ignore into teams values ("212", "national", "uruguay");
insert or ignore into teams values ("2570", "national", "uzbekistan");
insert or ignore into teams values ("213", "national", "venezuela");
insert or ignore into teams values ("4277", "national", "zambia");
insert or ignore into teams values ("2852", "national", "zimbabwe");
insert or ignore into teams values ("585", "national", "albania");
insert or ignore into teams values ("202", "national", "argentina");
insert or ignore into teams values ("579", "national", "armenia");
insert or ignore into teams values ("628", "national", "australia");
insert or ignore into teams values ("474", "national", "austria");
insert or ignore into teams values ("581", "national", "azerbaijan");
insert or ignore into teams values ("583", "national", "belarus");
insert or ignore into teams values ("459", "national", "belgium");
insert or ignore into teams values ("204", "national", "bolivia");
insert or ignore into teams values ("452", "national", "bosnia-herzegovina");
insert or ignore into teams values ("205", "national", "brazil");
insert or ignore into teams values ("462", "national", "bulgaria");
insert or ignore into teams values ("656", "national", "cameroon");
insert or ignore into teams values ("206", "national", "canada");
insert or ignore into teams values ("207", "national", "chile");
insert or ignore into teams values ("658", "national", "china");
insert or ignore into teams values ("208", "national", "colombia");
insert or ignore into teams values ("214", "national", "costa rica");
insert or ignore into teams values ("477", "national", "croatia");
insert or ignore into teams values ("445", "national", "cyprus");
insert or ignore into teams values ("450", "national", "czech republic");
insert or ignore into teams values ("479", "national", "denmark");
insert or ignore into teams values ("209", "national", "ecuador");
insert or ignore into teams values ("2620", "national", "egypt");
insert or ignore into teams values ("2650", "national", "el salvador");
insert or ignore into teams values ("448", "national", "england");
insert or ignore into teams values ("444", "national", "estonia");
insert or ignore into teams values ("458", "national", "finland");
insert or ignore into teams values ("478", "national", "france");
insert or ignore into teams values ("584", "national", "georgia");
insert or ignore into teams values ("481", "national", "germany");
insert or ignore into teams values ("455", "national", "greece");
insert or ignore into teams values ("2652", "national", "guatemala");
insert or ignore into teams values ("2654", "national", "haiti");
insert or ignore into teams values ("215", "national", "honduras");
insert or ignore into teams values ("480", "national", "hungary");
insert or ignore into teams values ("470", "national", "iceland");
insert or ignore into teams values ("4895", "national", "indonesia");
insert or ignore into teams values ("476", "national", "ireland");
insert or ignore into teams values ("461", "national", "israel");
insert or ignore into teams values ("162", "national", "italy");
insert or ignore into teams values ("4789", "national", "ivory coast");
insert or ignore into teams values ("627", "national", "japan");
insert or ignore into teams values ("2619", "national", "kazakhstan");
insert or ignore into teams values ("841", "national", "kuwait");
insert or ignore into teams values ("6724", "national", "kyrgyzstan");
insert or ignore into teams values ("456", "national", "latvia");
insert or ignore into teams values ("6640", "national", "lesotho");
insert or ignore into teams values ("589", "national", "liechtenstein");
insert or ignore into teams values ("460", "national", "lithuania");
insert or ignore into teams values ("582", "national", "luxembourg");
insert or ignore into teams values ("463", "national", "macedonia");
insert or ignore into teams values ("453", "national", "malta");
insert or ignore into teams values ("203", "national", "mexico");
insert or ignore into teams values ("483", "national", "moldova");
insert or ignore into teams values ("6775", "national", "montenegro");
insert or ignore into teams values ("449", "national", "netherlands");
insert or ignore into teams values ("657", "national", "nigeria");
insert or ignore into teams values ("586", "national", "northern ireland");
insert or ignore into teams values ("464", "national", "norway");
insert or ignore into teams values ("2841", "national", "oman");
insert or ignore into teams values ("2659", "national", "panama");
insert or ignore into teams values ("210", "national", "paraguay");
insert or ignore into teams values ("211", "national", "peru");
insert or ignore into teams values ("471", "national", "poland");
insert or ignore into teams values ("482", "national", "portugal");
insert or ignore into teams values ("11766", "national", "puerto rico");
insert or ignore into teams values ("4398", "national", "qatar");
insert or ignore into teams values ("473", "national", "romania");
insert or ignore into teams values ("454", "national", "russia");
insert or ignore into teams values ("588", "national", "san marino");
insert or ignore into teams values ("655", "national", "saudi arabia");
insert or ignore into teams values ("580", "national", "scotland");
insert or ignore into teams values ("6757", "national", "serbia");
insert or ignore into teams values ("468", "national", "slovakia");
insert or ignore into teams values ("472", "national", "slovenia");
insert or ignore into teams values ("467", "national", "south africa");
insert or ignore into teams values ("451", "national", "south korea");
insert or ignore into teams values ("164", "national", "spain");
insert or ignore into teams values ("466", "national", "sweden");
insert or ignore into teams values ("475", "national", "switzerland");
insert or ignore into teams values ("4396", "national", "thailand");
insert or ignore into teams values ("2627", "national", "trinidad & tobago");
insert or ignore into teams values ("465", "national", "turkey");
insert or ignore into teams values ("7507", "national", "turkmenistan");
insert or ignore into teams values ("457", "national", "ukraine");
insert or ignore into teams values ("660", "national", "united states");
insert or ignore into teams values ("212", "national", "uruguay");
insert or ignore into teams values ("2570", "national", "uzbekistan");
insert or ignore into teams values ("213", "national", "venezuela");
insert or ignore into teams values ("578", "national", "wales");
insert or ignore into teams values ("347", "eng", "cardiff city");
insert or ignore into teams values ("306", "eng", "hull city");
insert or ignore into teams values ("395", "eng", "watford");
insert or ignore into teams values ("331", "eng", "brighton & hove albion");
insert or ignore into teams values ("384", "eng", "crystal palace");
insert or ignore into teams values ("375", "eng", "leicester city");
insert or ignore into teams values ("358", "eng", "bolton wanderers");
insert or ignore into teams values ("393", "eng", "nottingham forest");
insert or ignore into teams values ("372", "eng", "charlton athletic");
insert or ignore into teams values ("374", "eng", "derby county");
insert or ignore into teams values ("379", "eng", "burnley");
insert or ignore into teams values ("392", "eng", "birmingham city");
insert or ignore into teams values ("357", "eng", "leeds united");
insert or ignore into teams values ("373", "eng", "ipswich town");
insert or ignore into teams values ("346", "eng", "blackpool");
insert or ignore into teams values ("369", "eng", "middlesbrough");
insert or ignore into teams values ("365", "eng", "blackburn rovers");
insert or ignore into teams values ("399", "eng", "sheffield wednesday");
insert or ignore into teams values ("335", "eng", "huddersfield town");
insert or ignore into teams values ("391", "eng", "millwall");
insert or ignore into teams values ("397", "eng", "barnsley");
insert or ignore into teams values ("342", "eng", "peterborough united");
insert or ignore into teams values ("380", "eng", "wolverhampton wanderers");
insert or ignore into teams values ("333", "eng", "bristol city");
insert or ignore into teams values ("279", "eng", "doncaster rovers");
insert or ignore into teams values ("349", "eng", "afc bournemouth");
insert or ignore into teams values ("337", "eng", "brentford");
insert or ignore into teams values ("284", "eng", "yeovil town");
insert or ignore into teams values ("398", "eng", "sheffield united");
insert or ignore into teams values ("341", "eng", "swindon town");
insert or ignore into teams values ("309", "eng", "leyton orient");
insert or ignore into teams values ("390", "eng", "milton keynes dons");
insert or ignore into teams values ("401", "eng", "walsall");
insert or ignore into teams values ("2594", "eng", "crawley town");
insert or ignore into teams values ("345", "eng", "tranmere rovers");
insert or ignore into teams values ("340", "eng", "notts county");
insert or ignore into teams values ("396", "eng", "crewe alexandra");
insert or ignore into teams values ("394", "eng", "preston north end");
insert or ignore into teams values ("388", "eng", "coventry city");
insert or ignore into teams values ("302", "eng", "shrewsbury town");
insert or ignore into teams values ("322", "eng", "carlisle united");
insert or ignore into teams values ("285", "eng", "stevenage");
insert or ignore into teams values ("332", "eng", "oldham athletic");
insert or ignore into teams values ("339", "eng", "colchester united");
insert or ignore into teams values ("313", "eng", "scunthorpe united");
insert or ignore into teams values ("354", "eng", "bury");
insert or ignore into teams values ("323", "eng", "hartlepool united");
insert or ignore into teams values ("385", "eng", "portsmouth");
insert or ignore into teams values ("389", "eng", "gillingham");
insert or ignore into teams values ("402", "eng", "rotherham united");
insert or ignore into teams values ("348", "eng", "port vale");
insert or ignore into teams values ("2567", "eng", "burton albion");
insert or ignore into teams values ("320", "eng", "cheltenham town");
insert or ignore into teams values ("353", "eng", "northampton town");
insert or ignore into teams values ("387", "eng", "bradford city");
insert or ignore into teams values ("343", "eng", "chesterfield");
insert or ignore into teams values ("311", "eng", "oxford united");
insert or ignore into teams values ("324", "eng", "exeter city");
insert or ignore into teams values ("310", "eng", "southend united");
insert or ignore into teams values ("303", "eng", "rochdale");
insert or ignore into teams values ("3891", "eng", "fleetwood town");
insert or ignore into teams values ("308", "eng", "bristol rovers");
insert or ignore into teams values ("344", "eng", "wycombe wanderers");
insert or ignore into teams values ("278", "eng", "morecambe");
insert or ignore into teams values ("315", "eng", "york city");
insert or ignore into teams values ("2731", "eng", "accrington stanley");
insert or ignore into teams values ("321", "eng", "torquay united");
insert or ignore into teams values ("3802", "eng", "afc wimbledon");
insert or ignore into teams values ("307", "eng", "plymouth argyle");
insert or ignore into teams values ("275", "eng", "dagenham & redbridge");
insert or ignore into teams values ("280", "eng", "barnet");
insert or ignore into teams values ("632", "eng", "aldershot town");
insert or ignore into teams values ("304", "eng", "mansfield town");
insert or ignore into teams values ("319", "eng", "kidderminster harriers");
insert or ignore into teams values ("635", "eng", "newport county");
insert or ignore into teams values ("386", "eng", "grimsby town");
insert or ignore into teams values ("352", "eng", "wrexham");
insert or ignore into teams values ("287", "eng", "hereford united");
insert or ignore into teams values ("301", "eng", "luton town");
insert or ignore into teams values ("4236", "eng", "dartford");
insert or ignore into teams values ("3828", "eng", "braintree town");
insert or ignore into teams values ("282", "eng", "forest green rovers");
insert or ignore into teams values ("316", "eng", "macclesfield town");
insert or ignore into teams values ("290", "eng", "woking");
insert or ignore into teams values ("351", "eng", "cambridge united");
insert or ignore into teams values ("3165", "eng", "alfreton town");
insert or ignore into teams values ("314", "eng", "lincoln city");
insert or ignore into teams values ("3138", "eng", "gateshead");
insert or ignore into teams values ("283", "eng", "nuneaton town");
insert or ignore into teams values ("13298", "eng", "hyde");
insert or ignore into teams values ("645", "eng", "tamworth");
insert or ignore into teams values ("286", "eng", "southport");
insert or ignore into teams values ("400", "eng", "stockport county");
insert or ignore into teams values ("642", "eng", "barrow");
insert or ignore into teams values ("640", "eng", "ebbsfleet united");
insert or ignore into teams values ("10183", "eng", "afc telford united");
insert or ignore into teams values ("9720", "usa", "montreal impact");
insert or ignore into teams values ("190", "usa", "new york red bulls");
insert or ignore into teams values ("6077", "usa", "houston");
insert or ignore into teams values ("186", "usa", "kansas city");
insert or ignore into teams values ("10739", "usa", "philadelphia union");
insert or ignore into teams values ("189", "usa", "new england");
insert or ignore into teams values ("183", "usa", "columbus");
insert or ignore into teams values ("182", "usa", "chicago");
insert or ignore into teams values ("7318", "usa", "toronto fc");
insert or ignore into teams values ("193", "usa", "dc united");
insert or ignore into teams values ("7318", "usa", "toronto fc");
insert or ignore into teams values ("187", "usa", "los angeles");
insert or ignore into teams values ("185", "usa", "fc dallas");
insert or ignore into teams values ("9726", "usa", "seattle sounders fc");
insert or ignore into teams values ("184", "usa", "colorado");
insert or ignore into teams values ("4771", "usa", "real salt lake");
insert or ignore into teams values ("191", "usa", "san jose");
insert or ignore into teams values ("4772", "usa", "chivas usa");
insert or ignore into teams values ("9723", "usa", "portland timbers");
insert or ignore into teams values ("9727", "usa", "vancouver whitecaps");

/* COUNTRY TABLE */
CREATE table countries (
    country TEXT PRIMARY KEY,
    name TEXT
);
/* EACH ROW IS A COUNTRY WE HAVE TEAMS IN */
insert or ignore into countries values ('usa', 'united states');
insert or ignore into countries values ('eng', 'england');
insert or ignore into countries values ('national', 'national teams');
insert or ignore into countries values ('fra', 'france');
insert or ignore into countries values ('ger', 'germany');
insert or ignore into countries values ('ned', 'netherlands');
insert or ignore into countries values ('por', 'portugal');
insert or ignore into countries values ('esp', 'spain');
insert or ignore into countries values ('ita', 'italy');
insert or ignore into countries values ('sco', 'scotland');
insert or ignore into countries values ('rus', 'russia');
insert or ignore into countries values ('mex', 'mexico');
